server:
  port: 8081
spring:
  application:
    name: ms-kajita-service
  config:
    import: "optional:configserver:http://root:123456@localhost:7070"
  profiles:
      active: development


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ms_kajita?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
